apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: denisemwangi/yolo-client:v1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://34.59.94.150:30001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: yolo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
